// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3RT01zZ65wh4yXTmZCPWZ_8S3vb-GoYM',
    appId: '1:873603815277:web:d535927e1d98b99f28ac64',
    messagingSenderId: '873603815277',
    projectId: 'mambusao-food-hub',
    authDomain: 'mambusao-food-hub.firebaseapp.com',
    storageBucket: 'mambusao-food-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXqpZc8W3Tl-XAcQ6VU9_sqyFdEkOpBt0',
    appId: '1:873603815277:android:24e9c7989ad605fd28ac64',
    messagingSenderId: '873603815277',
    projectId: 'mambusao-food-hub',
    storageBucket: 'mambusao-food-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI869FGWSPfRgfmeofXoe_y6qhoYAIUpc',
    appId: '1:873603815277:ios:a1ad0268675cc9cc28ac64',
    messagingSenderId: '873603815277',
    projectId: 'mambusao-food-hub',
    storageBucket: 'mambusao-food-hub.firebasestorage.app',
    iosBundleId: 'com.example.mambusaoFoodHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI869FGWSPfRgfmeofXoe_y6qhoYAIUpc',
    appId: '1:873603815277:ios:a1ad0268675cc9cc28ac64',
    messagingSenderId: '873603815277',
    projectId: 'mambusao-food-hub',
    storageBucket: 'mambusao-food-hub.firebasestorage.app',
    iosBundleId: 'com.example.mambusaoFoodHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3RT01zZ65wh4yXTmZCPWZ_8S3vb-GoYM',
    appId: '1:873603815277:web:3fc40bcae8bf90f228ac64',
    messagingSenderId: '873603815277',
    projectId: 'mambusao-food-hub',
    authDomain: 'mambusao-food-hub.firebaseapp.com',
    storageBucket: 'mambusao-food-hub.firebasestorage.app',
  );
}